version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    image: ghcr.io/rusiruchapana/test-full-flow:dev
    container_name: backend-dev
    restart: unless-stopped
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    image: ghcr.io/rusiruchapana/test-full-flow-frontend:dev
    container_name: frontend-dev
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"
    networks:
      - app-network


  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d:ro

    depends_on:
      - frontend
      - backend

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge