name: Build and deploy to vps

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - qa
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: test-full-flow

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: |
            ${{env.REGISTRY}}/${{env.IMAGE_NAME}}:${{github.ref_name}}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-to-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-and-push-image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy to dev EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_EC2_KEY }}
          port: ${{ secrets.DEV_PORT }}
          script: |
            set -e
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            docker stop app-dev || true
            docker rm app-dev || true
            docker run -d \
              --name app-dev \
              --restart unless-stopped \
              -p 7070:80 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}


  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push-image
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to production EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_EC2_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            set -e
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            docker stop app-prod || true
            docker rm app-prod || true
            docker run -d \
              --name app-prod \
              --restart unless-stopped \
              -p 7072:80 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
