name: Deploy

on:

  push:
    branches:
      - feature/test1

  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  

jobs:
  build-and-push:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:dev
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:dev
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-frontend:${{ github.sha }}

  deploy:
    #needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "chmod completed successfully"
          #ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts


      # - name: Copy compose file and nginx config
      #   run: |
      #     scp -i ~/.ssh/id_rsa docker-compose.dev.yml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/test-full-flow/docker-compose.dev.yml
      #     scp -i ~/.ssh/id_rsa -r nginx ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/test-full-flow/

      # - name: Deploy to dev EC2
      #   run: |
      #     ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "
      #       cd /var/www/test-full-flow &&
      #       docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAT_TOKEN }} &&
      #       docker compose -f docker-compose.dev.yml up -d --pull always
      #     "